---
services:
  perceived-temp-service:
    image: perceived-temp-service:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
      - 'KAFKA_TOPIC=${KAFKA_TOPIC}'
    deploy:
      replicas: 1